spring:
  application:
    name: ahenao-joanorduz-prietojoshua

  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config
  profiles:
    active: native

server:
  port: 8888