eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:9989/eureka/}
  instance:
    prefer-ip-address: true

## Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Taller De Microservicios
    description: Taller de Microservicios en clase - punto 1 - Joshua Prieto, Joan Orduz, Andres Henao